spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/board
    username: root
    password: 1
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 186930369763-oubl4ch9f0u3rdtbl1l0bg9scm120lil.apps.googleusercontent.com
            client-secret: wLCBrXPKwXCvOQC-n4k4OFUv
          facebook:
            client-id: 264391984216341
            client-secret: aeef8888bc32e4e2018fcfddaf2c7fa1
custom:
  oauth2:
    kakao:
      client-id: 972d5cfb1704ec88d67663a7a9e8198e